/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/alec/Dropbox/WPI/junior/bterm/rbe3002/labs/turtlebot_labs/src/lab3/srv/astar.srv
 *
 */


#ifndef LAB3_MESSAGE_ASTAR_H
#define LAB3_MESSAGE_ASTAR_H

#include <ros/service_traits.h>


#include <lab3/astarRequest.h>
#include <lab3/astarResponse.h>


namespace lab3
{

struct astar
{

typedef astarRequest Request;
typedef astarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct astar
} // namespace lab3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab3::astar > {
  static const char* value()
  {
    return "4ce05851504fd5efe880feba37418384";
  }

  static const char* value(const ::lab3::astar&) { return value(); }
};

template<>
struct DataType< ::lab3::astar > {
  static const char* value()
  {
    return "lab3/astar";
  }

  static const char* value(const ::lab3::astar&) { return value(); }
};


// service_traits::MD5Sum< ::lab3::astarRequest> should match 
// service_traits::MD5Sum< ::lab3::astar > 
template<>
struct MD5Sum< ::lab3::astarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab3::astar >::value();
  }
  static const char* value(const ::lab3::astarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab3::astarRequest> should match 
// service_traits::DataType< ::lab3::astar > 
template<>
struct DataType< ::lab3::astarRequest>
{
  static const char* value()
  {
    return DataType< ::lab3::astar >::value();
  }
  static const char* value(const ::lab3::astarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab3::astarResponse> should match 
// service_traits::MD5Sum< ::lab3::astar > 
template<>
struct MD5Sum< ::lab3::astarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab3::astar >::value();
  }
  static const char* value(const ::lab3::astarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab3::astarResponse> should match 
// service_traits::DataType< ::lab3::astar > 
template<>
struct DataType< ::lab3::astarResponse>
{
  static const char* value()
  {
    return DataType< ::lab3::astar >::value();
  }
  static const char* value(const ::lab3::astarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB3_MESSAGE_ASTAR_H
